### ISSUE TITLE
LeafNode not targeted correctly

### ISSUE THREAD

**Issue by hramir24-ford** [bkrem/react-d3-tree#395]
[Allows for additional className(s) to be passed to all leaf nodes (nodes without children).](https://bkrem.github.io/react-d3-tree/docs/interfaces/_tree_types_.treeprops.html#leafnodeclassname)

The link above defines leafnodes as nodes without children.
however.

```
 {
          name: 'Foreman',
          attributes: {
            department: 'Fabrication',
          },
          children: [
            {
              name: 'Worker',
              children: []
            }
          ]
}
```
having data in the  example above.
essentially a node with the children property but is just an empty array.
should technically count as a leaf node.

however as of `react-d3-tree - v3.3.2` this is not the case.
it will consider the worker node a branch node 

adding the `leafNodeClassName` property to the tree will not target the worker node correctly.

steps to reproduce
```
css ---
.node__root > circle {
  fill: red;
}

.node__branch > circle {
  fill: yellow;
}

.node__leaf > circle {
  fill: green;
  /* 
}
css --

function DTree() {
let data =   {
          name: 'Foreman',
          attributes: {
            department: 'Fabrication',
          },
          children: [
            {
              name: 'Worker',
              children: []
            }
          ]
}


 return <Tree data={data}
                          orientation={"vertical"}
                          rootNodeClassName="node__root"
                          branchNodeClassName="node__branch"
                          leafNodeClassName="node__leaf"
}
```

offending function appears to be this.
```
getNodeClassName = (parent: HierarchyPointNode<TreeNodeDatum>, nodeDatum: TreeNodeDatum) => {
    const { rootNodeClassName, branchNodeClassName, leafNodeClassName } = this.props;
    const hasParent = parent !== null && parent !== undefined;
    if (hasParent) {
      return nodeDatum.children ? branchNodeClassName : leafNodeClassName;
    } else {
      return rootNodeClassName;
    }
  };
  src/Tree/index.tsx 
  lines 486-494
```

truthy check on 
`return nodeDatum.children ? branchNodeClassName : leafNodeClassName;`

**Comment by bkrem** [comment]
Fixed in https://github.com/bkrem/react-d3-tree/releases/tag/v3.3.5

**Comment by Parya-Jafari** [comment]
This issue seems to still persist. Setting `leafNodeClassName` as a prop for `Tree` does not work when leaf nodes' `children` is an empty array `[]`. The fix in https://github.com/bkrem/react-d3-tree/pull/408 fixed the implementation in `src/Node/index.tsx`, however, the `nodeClassName` used in `Node/index.tsx` is passed down from the `Tree/index.tsx` in which the same implementation bug still persists
 [`getClassName`](in https://github.com/bkrem/react-d3-tree/blob/e67115aff35dfc77cfedfad0f17f65f89d716ef9/src/Tree/index.tsx#L519 ) in `Tree/index.tsx`: 
```
  getNodeClassName = (parent: HierarchyPointNode<TreeNodeDatum>, nodeDatum: TreeNodeDatum) => {
    const { rootNodeClassName, branchNodeClassName, leafNodeClassName } = this.props;
    const hasParent = parent !== null && parent !== undefined;
    if (hasParent) {
      return nodeDatum.children ? branchNodeClassName : leafNodeClassName;
    } else {
      return rootNodeClassName;
    }
  };
```

`nodeDatum.children ? branchNodeClassName : leafNodeClassName;` should be replaced with:
`nodeDatum.children && nodeDatum.children.length > 0 ? branchNodeClassName : leafNodeClassName;`
